### ISSUE TITLE
feature profiles: slash missing?

### ISSUE THREAD

**Issue by cmohorea** [netascode/nac-collector#47]
Slash missing (after "/transport" in e.g. "https://manager.sdwan.cisco.com/dataservice/v1/feature-profile/sdwan/transportbe789a1c-e7c2-40fd-b3a3-488b121cfb6b") and maybe error handling is needed?
```
2024-08-09 11:17:18,423 - nac_collector.cisco_client - INFO - GET /v1/config-group/ succeeded with status code 200
2024-08-09 11:17:18,582 - nac_collector.cisco_client - ERROR - GET https://manager.sdwan.cisco.com/dataservice/v1/feature-profile/sdwan/transportbe789a1c-e7c2-40fd-b3a3-488b121cfb6b returned an unexpected status code: 404
2024-08-09 11:17:18,648 - nac_collector.cisco_client - ERROR - GET https://manager.sdwan.cisco.com/dataservice/v1/feature-profile/sdwan/transportbe789a1c-e7c2-40fd-b3a3-488b121cfb6b returned an unexpected status code: 404
2024-08-09 11:17:18,711 - nac_collector.cisco_client - ERROR - GET https://manager.sdwan.cisco.com/dataservice/v1/feature-profile/sdwan/transportbe789a1c-e7c2-40fd-b3a3-488b121cfb6b returned an unexpected status code: 404
2024-08-09 11:17:18,775 - nac_collector.cisco_client - ERROR - GET https://manager.sdwan.cisco.com/dataservice/v1/feature-profile/sdwan/transportbe789a1c-e7c2-40fd-b3a3-488b121cfb6b returned an unexpected status code: 404
2024-08-09 11:17:18,842 - nac_collector.cisco_client - ERROR - GET https://manager.sdwan.cisco.com/dataservice/v1/feature-profile/sdwan/transportbe789a1c-e7c2-40fd-b3a3-488b121cfb6b returned an unexpected status code: 404
Traceback (most recent call last):
  File "/home/dev/tf2/bin/nac-collector", line 8, in <module>
    sys.exit(main())
  File "/home/dev/tf2/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/dev/tf2/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/dev/tf2/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dev/tf2/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/dev/tf2/lib/python3.8/site-packages/nac_collector/cli/main.py", line 112, in main
    final_dict = client.get_from_endpoints(endpoints_yaml_file)
  File "/home/dev/tf2/lib/python3.8/site-packages/nac_collector/cisco_client_sdwan.py", line 157, in get_from_endpoints
    endpoint_dict = self.get_feature_profiles(endpoint, endpoint_dict)
  File "/home/dev/tf2/lib/python3.8/site-packages/nac_collector/cisco_client_sdwan.py", line 311, in get_feature_profiles
    for k, v in response.json().items():
AttributeError: 'list' object has no attribute 'json'
```

**Comment by tzarski0** [comment]
Fixed.
